#include <css.h>
CSS::CSS() {}
const char *CSS::getCSS()
{
	return ".content-wrapper {"
		   "    max-width: 390px;"
		   "    margin: 0 auto;"
		   "    position: relative;"
		   "    padding: 20px;"
		   "}"
		   ".label {"
		   "    display: block;"
		   "    font: 14px helvetica;"
		   "    text-transform: uppercase;"
		   "    color: #fff;"
		   "    font-weight: 700;"
		   "    text-shadow: #000 0px 1px 2px;"
		   "    margin: 20px 0 10px 0;"
		   "}"
		   "input[type=\"range\"] {"
		   "    height: 26px;"
		   "    border-radius: 13px;"
		   "    -webkit-appearance: none;"
		   "    -moz-appearance: none;"
		   "    appearance: none;"
		   "    box-sizing: border-box;"
		   "    width: 100%;"
		   "    padding: 2px;"
		   "    margin: 10px 0 0 0;"
		   "    box-shadow: inset 4px 6px 10px -4px rgba(0, 0, 0, 0.3), 0 1px 1px -1px rgba(255, 255, 255, 0.3);"
		   "    background: rgba(228, 151, 151, 0.2);"
		   "    overflow: hidden;"
		   "    outline: none;"
		   "    border: 2px solid rgb(255,255,255);"
		   "}"
		   "input[type=\"range\"]::-webkit-slider-thumb {"
		   "    border-radius: 13px;"
		   "    -webkit-appearance: none;"
		   "    -moz-appearance: none;"
		   "    appearance: none;"
		   "    width: 20px;"
		   "    height: 20px;"
		   "    background: #333;"
		   "    position: relative;"
		   "    z-index: 3;"
		   "    box-shadow: inset 4px 6px 10px -4px rgba(0, 0, 0, 0.3), 0 1px 1px -1px rgba(255, 255, 255, 0.3);"
		   "}"
		   "input[type=\"range\"]::-webkit-slider-thumb:hover {"
		   "    cursor: pointer;"
		   "}"
		   "input[type=range]::-moz-range-track {"
		   "    height: 100%;"
		   "    background: transparent;"
		   "}"
		   "input[type=range]::-moz-range-thumb {"
		   "    border: none;"
		   "    height: 16px;"
		   "    width: 16px;"
		   "    border-radius: 50%;"
		   "    background: #fff;"
		   "}"
		   "input[type=range]::-moz-range-thumb:after {"
		   "    content: \" \";"
		   "    background: -moz-linear-gradient(top, rgba(116, 252, 250, 1) 0%, rgba(89, 205, 247, 1) 50%, rgba(54, 200, 237, 1) 52%, rgba(34, 244, 230, 1) 100%);"
		   "}"
		   "#demoWheel svg {"
		   "    margin: 0 auto;"
		   "}"
		   "";
}
