// ----------------------------------------------
// This file is auto-generated by web/index.js
// ----------------------------------------------


#ifndef html_c
#define html_c
class HTML{
public:
HTML();
const char *getHTML();
};
#endif
